### ISSUE TITLE
(3) osc message receiveing

### ISSUE THREAD

**Issue by panavrin** [panavrin/live-writing-osc#3]
(3) Using OSC, sent from a local app to Chrome, to emulate mouse behaviour.  

I have tested /camrotate and /zoomin.  No effect in Chrome browser.  However, I am getting feedback in the Terminal window, while sending these message from Max.
App says [ '/zoomin', 0 ]
App says [ '/zoomin', 1 ]
App says [ '/camrotate', 0 ]
App says [ '/camrotate', 1 ]

**Comment by panavrin** [comment]
This is because the live writing cannot receive OSC messages while node received the OSC message. Please be careful when you launch it. 

Before you run node server.js close the livewriting webpage tab in Chrome. 
Run the node server. 
And then open the livewriting webpage localhost:8080
You will see the OSC messages in the last row of debugging table.

**Comment by dandrewstewart** [comment]
Sending OSC from App to LW is working. Thank you.  I noticed that if I reload the page in Chrome, I have to quit the program in Terminal (ctrl C) and then "node server.js", again.  This is fine.  I'll just have to remember this. During the concert, I shouldn't have to reload the page.

**Comment by dandrewstewart** [comment]
/zoomin and /zoomout need to be switched;  that is to say, /zoomin creates a "zoom out", while /zoomout creates a "zoom in".    For example, when I /zoomin, the text becomes smaller. I would expect the reverse to happen – the text should become bigger.

**Comment by dandrewstewart** [comment]
Currently, for /camrotate and /camtranslate , values about zero move the text in one direction and values below zero move the text in the opposite direction. Importantly, increasing or decreasing currently have the "same effect", except when you go from values above zero to values below zero.  Instead of this type of mapping, is there any possibility of having a fixed range between, say, 0. to 1. (or -1. to 1.)? Furthermore, is it possible that when the value is increasing (e.g., 0.1…0.2…0.3…) the text moves one direction and when the values are decreasing (e.g., 0.3…0.2…0.2…) the text moves in the opposite direction?  In other words, a linear mapping would work much better with the MYO (accelerometer) data.  Alternatively, maintain the current mapping of values, which would work well with gyroscope data; and then, add the linear mapping I have described above, which would work better with accelerometer data.  Does this make sense?  

The same is true with /zoomin and /zoomout, but in this case, because you have two different OSC address spaces, the mapping of values is less problematic. However, I would still "love" to have a fixed range of values from 0. to 1. for /zoomin and /zoomout – or one OSC address that is /zoom, and increasing values zoom in and decreasing values zoom out.

NOTE:  I can always map my sensor data, in Max, to go beyond 1.0, or -1.0.  However, if we start with a "fixed" range (0. to 1., or -1 to 1.), then we have a good starting range.

**Comment by dandrewstewart** [comment]
Could you add a sort of "panic" OSC address to bring the text back to a "default position", in case I zoom or rotate the text too far off of the screen?

**Comment by dandrewstewart** [comment]
Could new OSC addresses be created to send text (back) into LW?  I realise this would appear to counteract the main interaction of your system;  however, I am envisioning this functionality as part of the **performance art** of working with LW – a further level of exploration where, perhaps, our writing is generated by gestures.  I suppose the metaphor would resemble the "mind" typing without actually seeing the person type.  Anyway, more concretely, I am wondering if we could OSC messages from my App to LW,  such as "/added/[line]/[ch]/[content]" and "/removed/[line]/[ch]/[content]"?

**Comment by panavrin** [comment]
- /panic is added 
- /zoomin and /zoomout is switched.

**Comment by panavrin** [comment]
for /added and /removed I have some questions. 

- `/added` how would you know where to add? line/ch? (or would you rather want to add content where the cursor is currently? )
- `/removed` it has the similar issue, how would your app know where to remove? (cuz you don't want to count the coordinate on the fly).  I guess I will do  `/removed/[startline]/[startch]/[endline]/[endch]` as you don't really know what content is there. 
- in general cursor control will be difficult.

**Comment by panavrin** [comment]
the initial version of `added/removed` is added. 
you can use as follows : 
`/added/hello/0/1` will add "hello" at line 0 and after the first letter. (1) 
`/added/hello` will add "hello" at which the cursor is. 
`/removed/1/2/1/4` will remove two letters from 2 at line 1. 

Let me know if you want to update this syntax.

**Comment by panavrin** [comment]
I changed the `camrotate` and `camtranslate` to use absolute values. 

In general, you can use the value between (-1,1) but you may have to scale them. 

Let me know how this goes.

**Comment by dandrewstewart** [comment]
Thanks Sang. Very nice. I'm making headway on the sound ideas, while you are modifying the programming. Where does "translate" come from, in /camtranslate.  Is this named after a particular principle in, say, physics or geometry?

- Could /zoom be created (instead of /zoomin and /zoomout) AND use the same absolute value system as /camrotate?

- Could we have one consistent range for the axes of /camrotate?  For example, I have noticed that with "no" zoom applied, the range of values for each axis of /camrotate is from 0. to 7.47 (or the same range in negative values).  This means, with no zoom, sending values from 0. to 7.47 rotates the text the full 360 degrees – aside, I thought this might mathematically related to, expressed in, radians, or something like that, but I don't think this is the case. Next, if zoom is applied, for example, zooming out, the range (0. to 7.47) is considerably reduced. The text rotates the full 360 degrees at a smaller value than 7.47.  This is obviously about the math;  however, from my end, having one consistent range (e.g., 0. to 7.47) would make the mapping easier, especially if I want to apply /zoom simultaneously.

**Comment by dandrewstewart** [comment]
No luck with:
/added/hello/0/1	Add "hello" at line 0 and after the first letter
/added/hello	Add "hello" at which the cursor is

Suggestions?

![screen shot 2017-05-01 at 22 43 36](https://cloud.githubusercontent.com/assets/28174995/25604542/4994eaae-2ec1-11e7-92f2-eed83e2e363c.png)

**Comment by panavrin** [comment]
oops my bad, it should have been separated by comma like the one you had with `/camtranslate`

This means that the content cannot contain "comma" cuz it will think the comma as a separator. Let me know if this is a problem. 

try the following? 
`/added,hello,0,1`
`/added,hello`

**Comment by panavrin** [comment]
close if this is resolved.
Otherwise, leave a comment and then remove the "Done" label. :)

**Comment by dandrewstewart** [comment]
I'm having trouble testing this in Max, because the comma in Max is used to separate a message into lists.  /added,hello  is transmitted as two messages:  first, /added and then, hello. I'm working on a solution in Max.  Why is the comma the solution for an OSC address?  Why not use forward slash?

**Comment by panavrin** [comment]
oh maybe it could have been just a space in between. the same syntax that
you use for /camrotate. how do you send /camrotate?

**Comment by panavrin** [comment]
Done is for me to tell you it is "done". :) 

You can close it if you think it is really done. (you have an authority to close an issue.)
